// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkw4mJp58ZiCBGlx2XL8ikz1_DDI5xPqk',
    appId: '1:292276574722:android:234e72940ef6c56af0e51b',
    messagingSenderId: '292276574722',
    projectId: 'flutter-login-shipper-app',
    storageBucket: 'flutter-login-shipper-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMGAD5NsJe5CaF4lRtimjS6OuQ0c_9ZA',
    appId: '1:292276574722:ios:ceb23079271bce9bf0e51b',
    messagingSenderId: '292276574722',
    projectId: 'flutter-login-shipper-app',
    storageBucket: 'flutter-login-shipper-app.appspot.com',
    androidClientId: '292276574722-2jmtvq5qh914ss1s02qgki8hq28a14b6.apps.googleusercontent.com',
    iosClientId: '292276574722-1a0gt24qa34rk2bso64p9vahsodhfqvb.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.vinEcommerce',
  );
}
